### ISSUE TITLE
Share only the word itself

### ISSUE THREAD

**Issue by dalb8** [caarmen/FRCAndroidWidget#17] opened 2015-06-10 12:51 UTC
Often, I must look up the word in the translator or dictionary so to make this quick, there should be an extra item when tapping the widget: to share just the word to an app such as Aard or WebSearch which would allow me to see the meaning. 

Another benefit of this is that the font can be hard to read: F looks like T for example. The item would let me see the word in the system font.

**Comment by caarmen** [comment] 2015-06-14 17:05
Hi Dalb8,

Thanks for the idea!  Actually, what I was thinking of doing was to add another item to open the word of the day in Wikipedia. I'll have to check if the words mostly have Wikipedia articles though.

As for the font, just for info, note that if you prefer, there is a "minimalist" widget which is a bit easier to read.  It doesn't have the scroll or the cursive font.

**Comment by dalb8** [comment] 2015-06-14 17:53
According to https://fr.m.wikipedia.org/wiki/Calendrier_r%C3%A9publicain all the words have an article. A handful would not have a link from there to a corresponding English article, mainly tools e.g https://fr.m.wikipedia.org/wiki/Houlette_(agriculture)#/languages. However in this case, Wiktionary does: https://fr.m.wiktionary.org/wiki/houlette

**Comment by caarmen** [comment] 2015-06-14 18:16
Thanks.  Actually I started to take a look at using web search instead.  It's much easier to implement :)  I think I'll go with that, at least for a first version.  

Then maybe later, I may take a look at using Wikipedia or Wiktionary... or some combined solution with a database of links for each word in each of the app's supported languages.

**Comment by dalb8** [comment] 2015-06-15 20:32
I installed v1.7.0 but when I try to look up the word, the popup says choose an app but below that, 'no apps are available'.

**Comment by caarmen** [comment] 2015-06-16 20:53
Argh :/  I'll take a look.  Thanks for reporting this!

**Comment by caarmen** [comment] 2015-06-21 15:26
I don't have any devices I want to put cyanogenmod on, for the moment.

But I've tested on:
* Google android emlator
* genymotion
* android x86 image (kitkat)
* android x86 image (donut)

And the browser came up on all these devices.

Been trying to figure out how to get CM12 in a virtual machine somehow, but no luck yet.

**Comment by caarmen** [comment] 2015-06-21 16:08
Well it looks like I can sort of reproduce this on my phone by disabling the "Google" app. I'll use this scenario as a basis for doing a fix :)

**Comment by caarmen** [comment] 2015-06-21 17:08
I've done a fix in version 1.7.1.  Hope this works for you now :)

You can wait for the update or go to the releases page to download it: https://github.com/caarmen/FRCAndroidWidget/releases/tag/release-1.7.1

**Comment by dalb8** [comment] 2015-06-23 12:18
Sorry I didn't mention I hadn't Gapps installed.

It works well for me now. Since it isn't a hyperlink, it will only work if I have an appropriate app installed like Aard or [WebSearch](http://balesz.github.io/android-WebSearch). As I noticed before, the Wikipedia app isn't available for these intents. 

The text shouldn't be capitalised because some words, like today's Véronique, are also *prénoms*.

**Comment by calvarez-ov** [comment] 2015-06-23 20:09
I'll make a "fix" for the upper-case/lower-case issue, but I personally think a reference app should handle ambiguity a bit better :stuck_out_tongue: 

I do see "Search Wikipedia" appear in the list of apps.  I installed Wikipedia from the Play Store though.  Maybe you have a FOSS version with fewer features? :stuck_out_tongue: 

I will keep the data as the single word.  If I decide to use links instead one day, it will be based on a database of links, probably Wikipedia.

**Comment by caarmen** [comment] 2015-06-23 20:36
I'll make a "fix" for the upper-case/lower-case issue, but I personally think a reference app should handle ambiguity a bit better :stuck_out_tongue:

I do see "Search Wikipedia" appear in the list of apps. I installed Wikipedia from the Play Store though. Maybe you have a FOSS version with fewer features? :stuck_out_tongue:

I will keep the data as the simple word (or words). If I decide to use links instead one day, it will be based on a database of links, probably Wikipedia.

**Comment by caarmen** [comment] 2015-06-23 20:42
To clarify, I've installed "Wikipedia Beta" from the Play Store.

**Comment by caarmen** [comment] 2015-06-23 20:50
If you're using the Wikipedia app from F-droid, it doesn't support the SEND action.  It's version 2.0-r-2014-10-14.

The latest version does support it: 2.0.103-beta-2015-06-11

Maybe you can submit a pull request to the guys at f-droid to update the description file, so everybody can benefit from an updated wikipedia: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.wikipedia.txt

**Comment by caarmen** [comment] 2015-07-19 12:13
Closing as lookup has been implemented:
* Lookup via web search if this is available
* Lookup lowercase word via ACTION_SEND if web search is not available.

The issue about Wikipedia not being in the list of ACTION_SEND supported apps is a limitation of the Wikipedia app, fixed in a more recent version of Wikipedia (which is not yet available on F-Droid).

**Closed by caarmen** 2015-07-19 12:13 UTC
